name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
